name: Security audit
on:
  schedule:
    # Run at 06:00 UTC every morning
    - cron: '0 6 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}